export function createPolymarketConfig(overrides = {}) {
  return {
    chainId: 137,
    clobHost: "https://clob.polymarket.com",
    gammaHost: "https://gamma-api.polymarket.com",
    dataApiHost: "https://data-api.polymarket.com",
    bridgeHost: "https://bridge.polymarket.com",
    relayerHost: "https://relayer-v2.polymarket.com",
    wsHost: "wss://ws-subscriptions-clob.polymarket.com/ws",
    proxyUrl: process.env.POLYMARKET_PROXY_URL ?? process.env.HTTPS_PROXY ?? process.env.HTTP_PROXY ?? null,
    requestTimeoutMs: Number(process.env.POLYMARKET_REQUEST_TIMEOUT_MS ?? 30000),
    minOrderSize: 1,
    maxBatchOrders: 15,
    geoAllowedCountries: null,
    geoDeniedCountries: null,
    risk: {
      enforcementMode: "warn-only",
      maxNotionalUsdPerOrder: 1000,
      maxNotionalUsdPerMarketPerDay: 5000,
      maxNotionalUsdPerSkillPerDay: 5000,
      maxDrawdownUsdPerDay: 1000,
      requireManualConfirmWhenOver: true,
    },
    retry: {
      retries: 3,
      baseDelayMs: 250,
      maxDelayMs: 5000,
      factor: 2,
    },
    submissionConfirm: {
      maxAttempts: 5,
      intervalMs: 2000,
      freshnessGraceMs: 2500,
      useNotifications: true,
      policy: "unique_order_id_evidence",
      maxWaitMs: 10000,
    },
    rateLimits: {
      clob: { requestsPerSecond: 15, concurrency: 6 },
      gamma: { requestsPerSecond: 10, concurrency: 4 },
      dataApi: { requestsPerSecond: 10, concurrency: 4 },
      bridge: { requestsPerSecond: 5, concurrency: 2 },
      relayer: { requestsPerSecond: 5, concurrency: 2 },
    },
    ws: {
      reconnectInitialDelayMs: 1000,
      reconnectMaxDelayMs: 30000,
      heartbeatIntervalMs: 15000,
      pongTimeoutMs: 10000,
    },
    endpoints: {
      gamma: {
        events: "/events",
        markets: "/markets",
        tags: "/tags",
        search: "/public-search",
        series: "/series",
        comments: "/comments",
        sports: "/sports",
        sportsMarketTypes: "/sports/market-types",
        teams: "/teams",
        publicProfile: "/public-profile",
      },
      dataApi: {
        trades: "/trades",
        positions: "/positions",
        activity: "/activity",
        value: "/value",
        holders: "/holders",
        closedPositions: "/closed-positions",
        traded: "/traded",
        leaderboard: "/v1/leaderboard",
        buildersLeaderboard: "/v1/builders/leaderboard",
        buildersVolume: "/v1/builders/volume",
        accountingSnapshot: "/v1/accounting/snapshot",
      },
      bridge: {
        supportedAssets: "/supported-assets",
        quote: "/quote",
        deposit: "/deposit",
        withdraw: "/withdraw",
        status: "/status",
      },
      relayer: {
        deployWallet: "/wallet/deploy",
        approve: "/tx/approve",
        split: "/tx/split",
        merge: "/tx/merge",
        redeem: "/tx/redeem",
        batch: "/tx/batch",
        txStatus: "/tx/status",
      },
    },
    ...overrides,
  };
}

export function mergeConfig(base, patch) {
  return {
    ...base,
    ...patch,
    retry: { ...base.retry, ...(patch?.retry ?? {}) },
    submissionConfirm: { ...base.submissionConfirm, ...(patch?.submissionConfirm ?? {}) },
    rateLimits: {
      clob: { ...base.rateLimits.clob, ...(patch?.rateLimits?.clob ?? {}) },
      gamma: { ...base.rateLimits.gamma, ...(patch?.rateLimits?.gamma ?? {}) },
      dataApi: { ...base.rateLimits.dataApi, ...(patch?.rateLimits?.dataApi ?? {}) },
      bridge: { ...base.rateLimits.bridge, ...(patch?.rateLimits?.bridge ?? {}) },
      relayer: { ...base.rateLimits.relayer, ...(patch?.rateLimits?.relayer ?? {}) },
    },
    risk: { ...base.risk, ...(patch?.risk ?? {}) },
    ws: { ...base.ws, ...(patch?.ws ?? {}) },
    endpoints: {
      gamma: { ...base.endpoints.gamma, ...(patch?.endpoints?.gamma ?? {}) },
      dataApi: { ...base.endpoints.dataApi, ...(patch?.endpoints?.dataApi ?? {}) },
      bridge: { ...base.endpoints.bridge, ...(patch?.endpoints?.bridge ?? {}) },
      relayer: { ...base.endpoints.relayer, ...(patch?.endpoints?.relayer ?? {}) },
    },
  };
}
